services:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 8883:8883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto_passwd:/mosquitto/config/mosquitto_passwd:ro
      - ./mosquitto/mosquitto.acl:/mosquitto/config/mosquitto.acl
      - ./mosquitto/mosquitto.pem:/mosquitto/config/mosquitto.pem
      - ./mosquitto/rootCA.pem:/mosquitto/config/rootCA.pem
      - ./mosquitto/mosquitto-key.pem:/mosquitto/config/mosquitto-key.pem
  
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telemetrix_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
  
  influxdb:
    image: influxdb:2
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telematrix
      - DOCKER_INFLUXDB_INIT_PASSWORD=#telematrix
      - DOCKER_INFLUXDB_INIT_ORG=telematrix
      - DOCKER_INFLUXDB_INIT_BUCKET=telematrix
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=telematrix==
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

volumes:
  pgdata_dev:
  influxdb2-data:
  influxdb2-config: